### PR TITLE
Revert "Merge pull request #9 from getlantern/harry/use-go-modules"

### PR DESCRIPTION
**Pull request by hwh33**
This reverts commit 6ca8e2aeb21fe6a7c7a96e292ce070a316b3b5c3, reversing
changes made to 038e6a8be68f44c66f88006d7ebc128805580f00.

Opening this and self-merging to notify.

@oxtoacart @joesis

### CODE REVIEW

**Comment by hwh33** [comment]
One of the CI checks failed due to a failure in TestReachServer.  As the tests passed in the other CI check, I'm going to chalk the failure up to a non-deterministic test and merge.

**Comment by joesis** [comment]
Sorry how could this be related to https://github.com/getlantern/autoupdate-server/commit/038e6a8be68f44c66f88006d7ebc128805580f00 ?

**Comment by hwh33** [comment]
Oh, that language is confusing.  That's part of the commit description, which was generated by `git` (using `git revert -m 1` as described [here](https://www.christianengvall.se/undo-pushed-merge-git/)).

What it's saying is something like, "This reverts <merge commit>, reversing changes made on top of <last commit before merge>".  Effectively, "This reverts commit 6ca8e2a, reversing changes made to master."

If you look at the current head of master, the changes by 038e6a8 are [still there](https://github.com/getlantern/autoupdate-server/blob/master/server/server.go#L19).

**Comment by joesis** [comment]
Haha sorry and thanks for the clarification @hwh33 !

**Comment by hwh33** [comment]
No worries and no problem!  I didn't read that part of the commit message when I opened this PR.  It was auto-generated and everything looked right in the diff.  When I saw your comment, I went back and read it and the wording confused me too.

**Pull request merged**
