### PR TITLE
Allow serve updates of both Lantern and Beam in a single autoupdate-server

### PR DESCRIPTION
**Pull request by joesis**
For https://github.com/getlantern/lantern-internal/issues/4195

Also does cleanups and migrates to go module

### CODE REVIEW

**Review by joesis — COMMENTED** [review]
There is no staging update server anymore but it's fairly straightforward to build a client to verify against production server once deployed.

**Review by hwh33 — APPROVED** [review]
LGTM, just needs a `go mod tidy`

**Comment by joesis** [comment]
> LGTM, just needs a `go mod tidy`

Just did it. Thanks @hwh33 ! Curious how you noticed it.

**Comment by joesis** [comment]
CI failure is because of GH rate limit. Merging and deploying.

**Comment by hwh33** [comment]
> Thanks @hwh33 ! Curious how you noticed it.

Just from my own experience with migrating repos to Go modules and forgetting to `go mod tidy` =)

**Comment by joesis** [comment]
Made a few hotfixes to allow deploying via Docker, mainly upgrading Go version to use go modules. Production is now failing because GitHub rate limit is hit again. Stopped the container for now and start it again 1 hour later.

**Comment by joesis** [comment]
Okay it's finally up and working.

**Pull request merged**
